# Site settings
title: "NYMNRC"
name: "NYMNRC"
images: "./assets/images"
url: "https://nymnrc.github.io"
permalink: /:title/
encoding: UTF-8

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false

sass:
  style: compressed

exclude:
  - README.MD

# Navigation Links
navigation_links:
  - title: About
    url: "#about"
  - title: Contact
    url: "#contact"
